### PR TITLE
Run tool plugins against all files at once when possible. 

### PR DESCRIPTION
**Pull request by tdenewiler**
Significantly speeds up the tool plugin runtime durations.

### CODE REVIEW

**Comment by tdenewiler** [comment]
After #62 is merged I will bring that into this branch/PR and the diff will be smaller.

**Comment by xydesa** [comment]
rstlint and writegood should also support linting multiple files at once. is there a reason you did not include those tools in this PR?

**Comment by tdenewiler** [comment]
For Markdown I like the [opensource.guide](https://github.com/github/opensource.guide) repo to test against since there are >200 files. I'll use that repo as a target for the writegood changes. Do you have any recommendations for a repo with a large amount of rst files? I looked for about 30 minutes last weekend and could not find one.

**Comment by xydesa** [comment]
> For Markdown I like the [opensource.guide](https://github.com/github/opensource.guide) repo to test against since there are >200 files. I'll use that repo as a target for the writegood changes. Do you have any recommendations for a repo with a large amount of rst files? I looked for about 30 minutes last weekend and could not find one.

This one seems to have a large number of rst files:
https://github.com/PointCloudLibrary/blog

**Comment by tdenewiler** [comment]
For writegood it already processes all files at once. I don't see a way to pass in multiple files at once to the rstlint interface. It has 'lint` and 'lint_file` that each take a single file at a time.

https://github.com/twolfson/restructuredtext-lint#documentation

I will work on updating the CHANGELOG with rstcheck updates. That is a good repo you found for rst sources.

**Comment by tdenewiler** [comment]
For the rstcheck testing I updated the documentation level with these changes:

```shell
diff --git a/statick_tool/rsc/config.yaml b/statick_tool/rsc/config.yaml
index 14c453e..85e2337 100644
--- a/statick_tool/rsc/config.yaml
+++ b/statick_tool/rsc/config.yaml
@@ -165,9 +165,13 @@ levels:
     discovery:
       markdown:
         flags: ""
+      rst:
+        flags: ""
     tool:
       markdownlint:
         flags: ""
+      rstcheck:
+        flags: ""
```

See CHANGELOG, but I also had a local fix in Statick `exceptions` module. One of the files in the example rst repo caused a `UnicodeDecodeError` assertion. I'll fix that later.

**Review by xydesa — APPROVED** [review]

**Pull request merged**
