### PR TITLE
Add Python 3.10 support. Use quotes for version numbers in YAML.

### PR DESCRIPTION
**Pull request by tdenewiler**

### CODE REVIEW

**Review by gregtkogut — APPROVED** [review]

**Comment by gregtkogut** [comment]
lgtm

**Comment by gregtkogut** [comment]
The workflow failure appears unrelated...should we fix that in another issue?

**Comment by tdenewiler** [comment]
I'm not sure what to do about the workflow failures. I'm okay merging this now or waiting until @xydesa is back and has a chance to look at it. The soft deadline I am trying to hit for these changes is EOL of Python 3.6 as discussed in sscpac/statick#376.

**Comment by gregtkogut** [comment]
lgtm

**Pull request merged**
